export type SelectType =
    | 'lamp'
    | 'cieX'
    | 'cieY'
    | 'colorTemp'
    | 'dimmer'
    | 'hue'
    | 'saturation'
    | 'sensor'
    | 'button0'
    | 'button1'
    | 'button2'
    | 'button3'
    | 'doorbell'
    | 'binarySensor'
    | 'smokeAlarm'
    | 'awayButton';
